branches:
  only:
  - master
  - staging
  - dev

language: bash

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
    docker build --no-cache -t databio/shinybase:latest . ;
    docker push databio/shinybase:latest;

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nmagee@virginia.edu
