name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build MASTER image
        id: img_build
        run: |
          docker build -t ghcr.io/databio/shinybase:latest .

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push :latest image to GHCR
        id: push_ghcr
        run: docker push ghcr.io/databio/shinybase:latest

      - name: Image digest
        run: echo ${{ steps.push_ghcr.outputs.digest }}
